version: "3.8"
services:
  lightbot-game:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    working_dir: /app
    command: npm start